<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SwebKit.Core\SwebKit.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="Azure.Monitor.Query" />
    <PackageReference Include="Azure.ResourceManager" />
    <PackageReference Include="Azure.ResourceManager.ApplicationInsights" />
  </ItemGroup>

</Project>
