<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SwebKit.Core\SwebKit.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" Version="1.18.0" />
    <PackageReference Include="Azure.Monitor.Query" Version="1.5.0" />
    <PackageReference Include="Azure.ResourceManager" Version="1.13.2" />
    <PackageReference Include="Azure.ResourceManager.ApplicationInsights" Version="1.1.0-beta.1" />
  </ItemGroup>

</Project>
